# Generated by Django 5.1.7 on 2025-03-09 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('disposition', models.CharField(choices=[('called', 'Called'), ('visited', 'Visited'), ('promise_to_pay', 'Promise to Pay')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('next_call_date', models.DateField(blank=True, null=True)),
                ('interaction_type', models.CharField(choices=[('field', 'Field'), ('calling', 'Calling')], default='field', max_length=50)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='loans.loan')),
            ],
            options={
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
    ]
