# Generated by Django 5.1.7 on 2025-03-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='customer',
        ),
        migrations.AddField(
            model_name='loan',
            name='customers',
            field=models.ManyToManyField(related_name='loans', to='customers.customer'),
        ),
    ]
